# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPCMEKSettingsConstraintV1
metadata:
  name: cmek_rotation
  annotations:
    description: Checks multiple CMEK key settings (protection level, algorithm, purpose,
      rotation period).
spec:
  severity: high
  match:
    ancestries:
    - "organizations/**"
  parameters:
    # Optionally specify the required key rotation period.  Default is 90 days
    # Valid time units are  "ns", "us", "ms", "s", "m", "h"
    # This is 90 days
    rotation_period: 2160h

    #Control ID: COM-CO-2.4
    #NIST 800-53: SC-12 SC-13
    #CRI Profile: PR.DS-1.1 PR.DS-1.2 PR.DS-2.1 PR.DS-2.2 PR.DS-5.1
    algorithm: GOOGLE_SYMMETRIC_ENCRYPTION

    #Control ID: COM-CO-2.5
    #NIST 800-53: SC-12 SC-13
    #CRI Profile: PR.DS-1.1 PR.DS-1.2 PR.DS-2.1 PR.DS-2.2 PR.DS-5.1
    purpose: ENCRYPT_DECRYPT

    #Control ID: COM-CO-2.6
    #NIST 800-53: SC-12 SC-13
    #CRI Profile: PR.DS-1.1 PR.DS-1.2 PR.DS-2.1 PR.DS-2.2 PR.DS-5.1
    protection_level: SOFTWARE
