# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
steps:
  # upload dataflow src file to bucket
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', './src', 'gs://bkt-n-ml-storage-akdv']

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', '-r', './data', 'gs://bkt-n-ml-storage-akdv']

  # compile pipeline
  - name: 'us-central1-docker.pkg.dev/prj-c-bu3artifacts-5wdo/c-publish-artifacts/vertexpipeline:v2'
    entrypoint: 'python'
    args: ['compile_pipeline.py']
    id: 'compile_job'

  # run pipeline
  - name: 'us-central1-docker.pkg.dev/prj-c-bu3artifacts-5wdo/c-publish-artifacts/vertexpipeline:v2'
    entrypoint: 'python'
    args: ['runpipeline.py']
    id: 'run_job'
    waitFor: ['compile_job']

  #   # upload pipeline yaml to composer
  # - name: 'gcr.io/cloud-builders/gsutil'
  #   args: ['cp', './common/vertex-ai-pipeline/pipeline_package.yaml', 'gs://us-central1-d-isolated-comp-8f58e4b5-bucket/dags/common/vertex-ai-pipeline/']
  #   id: 'upload_composer_file'

  #   # upload pipeline dag to composer
  # - name: 'gcr.io/cloud-builders/gsutil'
  #   args: ['cp', './composer/dags/dag.py', 'gs://us-central1-d-isolated-comp-8f58e4b5-bucket/dags/']
  #   id: 'upload dag'

options:
  logging: CLOUD_LOGGING_ONLY